In [179]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings 
warnings.filterwarnings("ignore")
%matplotlib inline

In [180]:
# data load
df = pd.read_excel("../data/data1.xlsx")

In [181]:
# rolling retention 구하기
# sign_up month만 가져오기
df["sign_up_month"] = df["sign_up"].dt.month
df["last_login_month"] = df["last_login"].dt.month

In [183]:
# pivot table
retention_df = pd.pivot_table(data=df, index="sign_up_month",
               columns="last_login_month", values="user_id", aggfunc = "count")

In [184]:
retention_df["합계"] = retention_df.sum(axis = 1)
retention_df.fillna(0, inplace = True)

In [185]:
# 월별 가입자
# pandas heatmap
retention_df.style.background_gradient(cmap='summer')

In [186]:
for idx in range(len(retention_df)):
    num = retention_df.iloc[idx, -1]
    for month in range(idx +1, 13):
        month_num = retention_df.loc[idx + 1, month]
        retention_df.loc[idx + 1, month] = num
        num -= month_num

In [187]:
# montly active user
retention_df.sum()

last_login_month
1       428.0
2       800.0
3      1230.0
4      1565.0
5      1931.0
6      2239.0
7      2513.0
8      2795.0
9      3130.0
10     3547.0
11     5447.0
12     7731.0
합계    10471.0
dtype: float64

In [188]:
for idx in range(len(retention_df)):
    num = retention_df.iloc[idx, -1]
    for month in range(idx +1, 13):
        month_num = retention_df.loc[idx + 1, month]
        retention_df.loc[idx + 1, month] = num
        num -= month_num


import copy
retention_df2 = copy.deepcopy(retention_df)

for i in range(len(retention_df2)):
    a = retention_df2.loc[i + 1, i+1]
    month += 1
    for col in range(1, 13):
        retention_df2.loc[i+1, col] = retention_df2.loc[i+1, col] / a

In [191]:

for i in range(len(retention_df2)):
    a = retention_df2.loc[i + 1, i+1]
    month += 1
    for col in range(1, 13):
        retention_df2.loc[i+1, col] = retention_df2.loc[i+1, col] / a

In [192]:
#  
retention_df2.style.background_gradient("summer")