In [65]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings 
warnings.filterwarnings("ignore")
%matplotlib inline

In [157]:
# data load
df = pd.read_excel("../data/data1.xlsx")

In [158]:
# rolling retention 구하기
# sign_up month만 가져오기
df["sign_up_month"] = df["sign_up"].dt.month
df["last_login_month"] = df["last_login"].dt.month

In [159]:
# pivot table
retention_df = pd.pivot_table(data=df, index="sign_up_month",
               columns="last_login_month", values="user_id", aggfunc = "count")

In [160]:
retention_df["합계"] = retention_df.sum(axis = 1)
retention_df.fillna(0, inplace = True)

In [161]:
# 월별 가입자
# pandas heatmap
retention_df.style.background_gradient(cmap='summer')

In [162]:
for idx in range(len(retention_df)):
    num = retention_df.iloc[idx, -1]
    for month in range(idx +1, 13):
        month_num = retention_df.loc[idx + 1, month]
        retention_df.loc[idx + 1, month] = num
        num -= month_num

In [165]:
# montly active user
retention_df.sum()

last_login_month,1,2,3,4,5,6,7,8,9,10,11,12,합계
sign_up_month,,,,,,,,,,,,,
1,428.0,319.0,298.0,252.0,224.0,182.0,163.0,139.0,119.0,101.0,79.0,59.0,428.0
2,0.0,481.0,387.0,353.0,328.0,291.0,269.0,235.0,201.0,176.0,145.0,111.0,481.0
3,0.0,0.0,545.0,459.0,432.0,397.0,360.0,334.0,293.0,251.0,208.0,171.0,545.0
4,0.0,0.0,0.0,501.0,417.0,383.0,361.0,325.0,290.0,261.0,218.0,184.0,501.0
5,0.0,0.0,0.0,0.0,530.0,456.0,419.0,390.0,363.0,330.0,283.0,238.0,530.0
6,0.0,0.0,0.0,0.0,0.0,530.0,446.0,417.0,386.0,357.0,330.0,291.0,530.0
7,0.0,0.0,0.0,0.0,0.0,0.0,495.0,421.0,389.0,363.0,332.0,308.0,495.0
8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,534.0,457.0,420.0,379.0,348.0,534.0
9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,632.0,551.0,507.0,473.0,632.0
10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,737.0,692.0,642.0,737.0
11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2274.0,2122.0,2274.0
12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2784.0,2784.0

In [166]:
import copy
retention_df2 = copy.deepcopy(retention_df)

In [176]:

for i in range(len(retention_df2)):
    a = retention_df2.loc[i + 1, i+1]
    month += 1
    for col in range(1, 13):
        retention_df2.loc[i+1, col] = retention_df2.loc[i+1, col] / a

In [178]:
#  
retention_df2.style.background_gradient("summer")