In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")
%matplotlib inline

In [2]:
df = pd.read_csv("../data/data2.csv")

In [5]:
import copy
new_df = copy.deepcopy(df)

In [10]:
lst_1 = [1, 2, 3, 4, 5, 6]
lst_2 = [2500, 2500, 2500, 2500, 2500, 2500]
df2 = pd.DataFrame({"sign_up_month":lst_1, "가입자":lst_2})

In [12]:
# 병합, rename
new_df2 = pd.concat([new_df, df2])
new_df2.rename({"sign_up_month": "가입월"}, axis = 1, inplace = True)

In [26]:
# 잔존율은 1년치 트렌드는 확인 가능
# 1 + 잔존율 1년 이상의 잔존율 : 10%
new_df2.iloc[0:6,2] = 0.1

# 잔존율 개선 5%
# 기존값 * (1 + 0.01*5)
new_df2.iloc[6:,2] = new_df.iloc[:, 2] * 1.05

In [30]:
# 1 + 결제 비율 45
new_df2.iloc[0:6,4] = 0.45

# 결제비율 개선 : 10%
# 기존값 * (1 + 0.01*10)
new_df2.iloc[6:,4] = new_df.iloc[:, 4] * 1.1

In [33]:
# ARPPU : 9300
new_df2.iloc[:, -2] = 9300

In [42]:
# 활동회원 = 가입자 * 잔존율
new_df2.loc[:, "활동회원"] = round(new_df2.loc[:, "가입자"] * new_df2.loc[:, "잔존율"], 0)

In [45]:
# 결제자수  = 활동회원 * 결제비율
new_df2.loc[:, "결제자수"] = round(new_df2.loc[:, "활동회원"] * new_df2.loc[:, "결제비율"], 0)

In [47]:
# 매출 = 결제자수 * ARPPU
new_df2.loc[:, "매출"] = round(new_df2.loc[:, "결제자수"] * new_df2.loc[:, "ARPPU"], 0)

In [ ]:
# 가입자수 개선 비율 등을 조절하면서 최종 매출에 어떠한 영향을 미치는지 확인
# 매출을 가장 높이는 변수를 KPI로 정하고 비즈니스에 활용

In [54]:
new_df2.reset_index(drop = True, inplace = True)

In [61]:
new_df2.style.background_gradient("summer")

In [49]:
# 최종 매출 합계
new_df2["매출"].sum()

34828500.0